(deftheme mytheme
  "Created 2015-04-11.")

(custom-theme-set-variables
 'mytheme
 '(ansi-color-names-vector ["#272822" "#F92672" "#A6E22E" "#E6DB74" "#66D9EF" "#FD5FF0" "#A1EFE4" "#F8F8F2"])
 '(compilation-message-face (quote default))
 '(fci-rule-color "#49483E"))

(custom-theme-set-faces
 'mytheme
 '(button ((t (:underline t))))
 '(region ((t (:inverse-video t :background "Blue"))))
 '(shadow ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(match ((((class color) (min-colors 257)) (:background "#49483E" :foreground "#F8F8F0" :weight bold)) (((class color) (min-colors 89)) (:background "#303030" :foreground "#FFFAFA" :weight bold))))
 '(cursor ((((class color) (min-colors 257)) (:foreground "gray50" :background "gray100" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(mouse ((((class color) (min-colors 257)) (:foreground "#272822" :background "#F8F8F2" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(fringe ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "gray100")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(highlight ((((class color) (min-colors 257)) (:background "#49483E")) (((class color) (min-colors 89)) (:background "#303030"))))
 '(link ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t :weight bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t :weight normal))))
 '(success ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(warning ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(error ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(lazy-highlight ((((class color) (min-colors 257)) (:foreground "#272822" :background "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#CDC673" :weight normal))))
 '(escape-glyph ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(compilation-column-number ((((class color) (min-colors 257)) (:inherit font-lock-doc-face :foreground "#A1EFE4" :underline nil)) (((class color) (min-colors 89)) (:inherit font-lock-doc-face :foreground "#5FFFFF" :underline nil))))
 '(compilation-error ((((class color) (min-colors 257)) (:inherit error :underline nil)) (((class color) (min-colors 89)) (:inherit error :underline nil))))
 '(compilation-info ((((class color) (min-colors 257)) (:foreground "#75715E" :underline nil :bold nil)) (((class color) (min-colors 89)) (:foreground "#8B8878" :underline nil :bold nil))))
 '(compilation-line-number ((((class color) (min-colors 257)) (:foreground "#A6E22E" :underline nil)) (((class color) (min-colors 89)) (:foreground "#87D700" :underline nil))))
 '(compilation-warning ((((class color) (min-colors 257)) (:inherit warning :underline nil)) (((class color) (min-colors 89)) (:inherit warning :underline nil))))
 '(compilation-mode-line-exit ((((class color) (min-colors 257)) (:inherit compilation-info :foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:inherit compilation-info :foreground "#87D700" :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 257)) (:inherit compilation-error :foreground "#F92672" :weight bold)) (((class color) (min-colors 89)) (:inherit compilation-error :foreground "#FF1493" :weight bold))))
 '(compilation-mode-line-run ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold))))
 '(diary ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 257)) (:foreground "#CDC673"))))
 '(dropdown-list-face ((((class color) (min-colors 257)) (:background "#49483E" :foreground "#A1EFE4")) (((class color) (min-colors 89)) (:background "#303030" :foreground "#5FFFFF"))))
 '(dropdown-list-selection-face ((((class color) (min-colors 257)) (:background "#349B8D" :foreground "#BBF7EF")) (((class color) (min-colors 89)) (:background "#BBF7EF" :foreground "#349B8D"))))
 '(isearch ((((class color) (min-colors 257)) (:foreground "#272822" :background "#FD5FF0" :weight normal)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#D700D7" :weight normal))))
 '(isearch-fail ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#272822" :bold t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :bold t))))
 '(menu ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(minibuffer-prompt ((((class color) (min-colors 257)) (:foreground "Black")) (((class color) (min-colors 89)) (:foreground "Black"))))
 '(mode-line ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "gray100" :background "gray70" :box (:line-width 1 :color "#3E3D31" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#F5F5F5" :background "#212121" :box (:line-width 1 :color "#212121" :style unspecified)))))
 '(mode-line-buffer-id ((((class color) (min-colors 257)) (:foreground "DodgerBlue" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(mode-line-inactive ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#75715E" :background "#272822" :box (:line-width 1 :color "#3E3D31" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#8B8878" :background "#1B1E1C" :box (:line-width 1 :color "#212121" :style unspecified)))))
 '(header-line ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#F8F8F0" :background "#49483E" :box (:line-width 1 :color "#49483E" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#FFFAFA" :background "#303030" :box (:line-width 1 :color "#303030" :style unspecified)))))
 ;; '(region ((t (:foreground "white" :background "dark slate gray"))))
 ;; '(region ((((class color) (min-colors 257)) (:background "" :inherit t)) (((class color) (min-colors 89)) (:background "#303030" :inherit t))))
 '(secondary-selection ((((class color) (min-colors 257)) (:background "#49483E" :inherit t)) (((class color) (min-colors 89)) (:background "#303030" :inherit t))))
 '(trailing-whitespace ((((class color) (min-colors 257)) (:background "#F92672")) (((class color) (min-colors 89)) (:background "#FF1493"))))
 '(vertical-border ((((class color) (min-colors 257)) (:foreground "#49483E")) (((class color) (min-colors 89)) (:foreground "#303030"))))
 '(font-lock-builtin-face ((((class color) (min-colors 257)) (:foreground "#F92672" :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-comment-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-constant-face ((((class color) (min-colors 257)) (:foreground "firebrick")) (((class color) (min-colors 89)) (:foreground "firebrick"))))
 ;; '(font-lock-doc-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-doc-face ((t (:foreground "#8D8D84" :slant italic))))
 '(font-lock-function-name-face ((t (:foreground "Black" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "blue3" :weight normal))))
 '(font-lock-preprocessor-face ((t (:foreground "#808080" :weight bold))))
 '(font-lock-string-face ((t (:foreground "dark slate gray"))))
 '(font-lock-type-face ((t (:foreground "dark magenta" :slant italic :weight normal))))
;; '(font-lock-variable-name-face ((t (:background "#eeeeee" :foreground "Black" :box (:line-width 1 :color "grey50") :weight normal))))
 '(font-lock-variable-name-face ((t (:foreground "Black" :underline t))))
 ;; '(font-lock-function-name-face ((t (:foreground "#00FF7F" :weight normal))))
 ;; '(font-lock-keyword-face ((((class color) (min-colors 257)) (:foreground "#F92672" :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-negation-char-face ((t (:foreground "#CDC673" :weight bold))))
 ;; '(font-lock-preprocessor-face ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 257)) (:foreground "#AE81FF" :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :weight normal))))
 ;; '(font-lock-string-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 ;; '(font-lock-type-face ((((class color) (min-colors 257)) (:foreground "#66D9EF" :italic nil)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :italic nil))))
 ;; '(font-lock-variable-name-face ((t (:background "light gray" :foreground "Black" :box (:line-width 1 :color "grey50") :weight normal)))))
 ;; '(font-lock-variable-name-face ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(font-lock-warning-face ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight bold :italic t :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold :italic t :underline t))))
 '(c-annotation-face ((((class color) (min-colors 257)) (:inherit font-lock-constant-face)) (((class color) (min-colors 89)) (:inherit font-lock-constant-face))))

 '(company-tooltip ((((class color) (min-colors 257)) (:background "#49483E" :foreground "#A1EFE4")) (((class color) (min-colors 89)) (:background "#303030" :foreground "#5FFFFF"))))
 '(company-tooltip-selection ((((class color) (min-colors 257)) (:background "#349B8D" :foreground "#BBF7EF")) (((class color) (min-colors 89)) (:background "#BBF7EF" :foreground "#349B8D"))))
 '(company-tooltip-mouse ((((class color) (min-colors 257)) (:background "#BBF7EF" :foreground "#349B8D")) (((class color) (min-colors 89)) (:background "#349B8D" :foreground "#BBF7EF"))))
 '(company-tooltip-common ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :underline t)) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :underline t))))
 '(company-tooltip-common-selection ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :underline t)) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :underline t))))
 '(company-preview ((((class color) (min-colors 257)) (:background "#49483E" :foreground "#A1EFE4")) (((class color) (min-colors 89)) (:background "#303030" :foreground "#5FFFFF"))))
 '(company-preview-common ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :underline t)) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :underline t))))
 '(company-scrollbar-bg ((((class color) (min-colors 257)) (:background "#6b6b6b")) (((class color) (min-colors 89)) (:background "#6c6c6c"))))
 '(company-scrollbar-fg ((((class color) (min-colors 257)) (:background "#968B26")) (((class color) (min-colors 89)) (:background "#968B26"))))


 '(custom-face-tag ((((class color) (min-colors 257)) (:inherit variable-pitch :height 1.2 :foreground "#AE81FF" :weight bold)) (((class color) (min-colors 89)) (:inherit variable-pitch :height 1.2 :foreground "#AF87FF" :weight bold))))
 '(custom-variable-tag ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#A1EFE4" :height 1.2)) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FFFFF" :height 1.2))))
 '(custom-comment-tag ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(custom-group-tag ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#66D9EF" :height 1.2)) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FD7FF" :height 1.2))))
 '(custom-group-tag-1 ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#F92672" :height 1.2)) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#FF1493" :height 1.2))))
 '(custom-state ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(diff-added ((((class color) (min-colors 257)) (:foreground "#A6E22E" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#87D700" :background "#1B1E1C"))))
 '(diff-changed ((((class color) (min-colors 257)) (:foreground "#66D9EF" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :background "#1B1E1C"))))
 '(diff-removed ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C"))))
 '(diff-header ((((class color) (min-colors 257)) (:background "#272822")) (((class color) (min-colors 89)) (:background "#1B1E1C"))))
 '(diff-file-header ((((class color) (min-colors 257)) (:background "#272822" :foreground "#F8F8F2" :weight bold)) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5" :weight bold))))
 '(diff-refine-added ((((class color) (min-colors 257)) :foreground "#272822" :background "#A6E22E") (((class color) (min-colors 89)) :foreground "#1B1E1C" :background "#87D700")))
 '(diff-refine-change ((((class color) (min-colors 257)) :foreground "#272822" :background "#66D9EF") (((class color) (min-colors 89)) :foreground "#1B1E1C" :background "#5FD7FF")))
 '(ido-first-match ((t (:foreground "magenta4" :weight normal))))
 ;; '(ido-first-match ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(ido-only-match ((((class color) (min-colors 257)) (:foreground "#272822" :background "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#CDC673" :weight normal))))
 '(ido-subdir ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(ido-incomplete-regexp ((((class color) (min-colors 257)) (:foreground "#F92672" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(ido-indicator ((((class color) (min-colors 257)) (:background "#F92672" :foreground "#272822" :width condensed)) (((class color) (min-colors 89)) (:background "#FF1493" :foreground "#1B1E1C" :width condensed))))
 '(ido-virtual ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(linum ((((class color) (min-colors 89)) (:foreground "gray50" :background "#eeeeee")) (((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C"))))
 '(magic-diff-none ((t (:foreground "gray10" :background "White"))))
 '(magit-item-highlight ((t (:foreground "Black" :background "#eeeeee"))))
 ;; '(magit-section-title ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 ;; '(magit-branch ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold))))
 ;; '(magit-log-author ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 ;; '(magit-log-graph ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 ;; '(magit-log-head-label-bisect-bad ((((class color) (min-colors 257)) (:background "#FC5C94" :foreground "#A20C41" :box 1)) (((class color) (min-colors 89)) (:background "#A20C41" :foreground "#FC5C94" :box 1))))
 ;; '(magit-log-head-label-bisect-good ((((class color) (min-colors 257)) (:background "#C1F161" :foreground "#67930F" :box 1)) (((class color) (min-colors 89)) (:background "#67930F" :foreground "#C1F161" :box 1))))
 ;; '(magit-log-head-label-default ((((class color) (min-colors 257)) (:background "#49483E" :box 1)) (((class color) (min-colors 89)) (:background "#303030" :box 1))))
 ;; '(magit-log-head-label-local ((((class color) (min-colors 257)) (:background "#21889B" :foreground "#8DE6F7" :box 1)) (((class color) (min-colors 89)) (:background "#8DE6F7" :foreground "#21889B" :box 1))))
 ;; '(magit-log-head-label-patches ((((class color) (min-colors 257)) (:background "#A20C41" :foreground "#FC5C94" :box 1)) (((class color) (min-colors 89)) (:background "#FC5C94" :foreground "#A20C41" :box 1))))
 ;; '(magit-log-head-label-remote ((((class color) (min-colors 257)) (:background "#67930F" :foreground "#C1F161" :box 1)) (((class color) (min-colors 89)) (:background "#C1F161" :foreground "#67930F" :box 1))))
 ;; '(magit-log-head-label-tags ((((class color) (min-colors 257)) (:background "#968B26" :foreground "#F3EA98" :box 1)) (((class color) (min-colors 89)) (:background "#F3EA98" :foreground "#968B26" :box 1))))
 ;; '(magit-log-sha1 ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(markdown-header-face ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(markdown-header-face-1 ((((class color) (min-colors 257)) (:inherit markdown-header-face :height 1.3)) (((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.3))))
 '(markdown-header-face-2 ((((class color) (min-colors 257)) (:inherit markdown-header-face :height 1.2)) (((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.2))))
 '(markdown-header-face-3 ((((class color) (min-colors 257)) (:inherit markdown-header-face :height 1.15)) (((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.15))))
 '(markdown-header-face-4 ((((class color) (min-colors 257)) (:inherit markdown-header-face :height 1.1)) (((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.1))))
 '(markdown-header-face-5 ((((class color) (min-colors 257)) (:inherit markdown-header-face)) (((class color) (min-colors 89)) (:inherit markdown-header-face))))
 '(markdown-header-face-6 ((((class color) (min-colors 257)) (:inherit markdown-header-face)) (((class color) (min-colors 89)) (:inherit markdown-header-face))))
 '(message-cited-text ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(message-header-name ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(message-header-other ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :weight normal)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-to ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :weight normal)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-cc ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :weight normal)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-newsgroups ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(message-header-subject ((((class color) (min-colors 257)) (:foreground "#A1EFE4" :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :weight normal))))
 '(message-header-xheader ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(message-mml ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(message-separator ((((class color) (min-colors 257)) (:foreground "#75715E" :slant italic)) (((class color) (min-colors 89)) (:foreground "#8B8878" :slant italic))))
 '(show-paren-match ((((class color) (min-colors 257)) (:foreground "#A1EFE4" :background "#272822" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(show-paren-mismatch ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#272822" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(speedbar-button-face ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#75715E")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#8B8878"))))
 '(speedbar-directory-face ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#66D9EF")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FD7FF"))))
 '(speedbar-file-face ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#F8F8F2")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#F5F5F5"))))
 '(speedbar-highlight-face ((((class color) (min-colors 257)) (:inherit variable-pitch :background "#49483E")) (((class color) (min-colors 89)) (:inherit variable-pitch :background "#303030"))))
 '(speedbar-selected-face ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#E6DB74" :underline t)) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#CDC673" :underline t))))
 '(speedbar-separator-face ((((class color) (min-colors 257)) (:inherit variable-pitch :background "#66D9EF" :foreground "#272822" :overline "#349B8D")) (((class color) (min-colors 89)) (:inherit variable-pitch :background "#5FD7FF" :foreground "#1B1E1C" :overline "#BBF7EF"))))
 '(speedbar-tag-face ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#A6E22E")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#87D700"))))
 '(tooltip ((((class color) (min-colors 257)) (:background "#968B26" :foreground "#F3EA98" :inherit variable-pitch))))
 '(which-func ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(default ((t (:foreground "Black"))))
 )

(provide-theme 'mytheme)
